version: '3.8'
services:
  api_gateway:
    build: ./api_service
    ports:
      - "8000:8000"
    restart: always  # Добавлено автоматическое перезапуск
    env_file:
      - ./api_service/.env
    depends_on:
      - user_service

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"  # Добавлен порт для отладки
    restart: always  # Добавлено автоматическое перезапуск
    env_file:
      - ./user_service/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
