# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from statistics_service.protos import statistics_pb2 as protos_dot_statistics__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/statistics.StatisticsService/GetPostStats',
                request_serializer=protos_dot_statistics__pb2.GetPostStatsRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetPostStatsResponse.FromString,
                _registered_method=True)
        self.GetPostViewsDynamics = channel.unary_unary(
                '/statistics.StatisticsService/GetPostViewsDynamics',
                request_serializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostLikesDynamics = channel.unary_unary(
                '/statistics.StatisticsService/GetPostLikesDynamics',
                request_serializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostCommentsDynamics = channel.unary_unary(
                '/statistics.StatisticsService/GetPostCommentsDynamics',
                request_serializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/statistics.StatisticsService/GetTopPosts',
                request_serializer=protos_dot_statistics__pb2.GetTopPostsRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetTopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/statistics.StatisticsService/GetTopUsers',
                request_serializer=protos_dot_statistics__pb2.GetTopUsersRequest.SerializeToString,
                response_deserializer=protos_dot_statistics__pb2.GetTopUsersResponse.FromString,
                _registered_method=True)


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Получение базовой статистики по посту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostViewsDynamics(self, request, context):
        """Получение динамики просмотров по посту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikesDynamics(self, request, context):
        """Получение динамики лайков по посту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostCommentsDynamics(self, request, context):
        """Получение динамики комментариев по посту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Получение топ 10 постов по метрике
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Получение топ 10 пользователей по метрике
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=protos_dot_statistics__pb2.GetPostStatsRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetPostStatsResponse.SerializeToString,
            ),
            'GetPostViewsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostViewsDynamics,
                    request_deserializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.SerializeToString,
            ),
            'GetPostLikesDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikesDynamics,
                    request_deserializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.SerializeToString,
            ),
            'GetPostCommentsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostCommentsDynamics,
                    request_deserializer=protos_dot_statistics__pb2.GetPostDynamicsRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetPostDynamicsResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=protos_dot_statistics__pb2.GetTopPostsRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetTopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=protos_dot_statistics__pb2.GetTopUsersRequest.FromString,
                    response_serializer=protos_dot_statistics__pb2.GetTopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statistics.StatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetPostStats',
            protos_dot_statistics__pb2.GetPostStatsRequest.SerializeToString,
            protos_dot_statistics__pb2.GetPostStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostViewsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetPostViewsDynamics',
            protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
            protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikesDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetPostLikesDynamics',
            protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
            protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostCommentsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetPostCommentsDynamics',
            protos_dot_statistics__pb2.GetPostDynamicsRequest.SerializeToString,
            protos_dot_statistics__pb2.GetPostDynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetTopPosts',
            protos_dot_statistics__pb2.GetTopPostsRequest.SerializeToString,
            protos_dot_statistics__pb2.GetTopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/GetTopUsers',
            protos_dot_statistics__pb2.GetTopUsersRequest.SerializeToString,
            protos_dot_statistics__pb2.GetTopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
